displayName: URLTest
testPlan: url_test.jmx
description: ''
engineInstances: 2
testId: 4c23188e-6525-4690-95b4-5b646f183028
testType: JMX
splitAllCSVs: False
failureCriteria:
- p90(response_time_ms) > 50
- percentage(error) > 10
autoStop:
  errorPercentage: 80
  timeWindow: 120
